openapi: 3.0.0
info:
  title: Express API Template
  description: This template is built with Express, TypeScript, MongoDB, EJS, and a whole lot more.
  version: 0.0.1


# servers:
#   - url: http://api.example.com/v1
#     description: Optional server description, e.g. Main (production) server
#   - url: http://staging-api.example.com
#     description: Optional server description, e.g. Internal staging server for testing

paths:
  /users/all:
    get:
      summary: Returns a list of users.
      description:
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string